# Importing Libraries

NumPy Python Standard Library içerisinde bulunan bir module değildir.

-->NumPy module'unu import etmek için önce ; NumPy module'unu Python pip aracı ile install etmemiz gerekiyor. "pip" aracı bize Standard Library'de bulunmayan module'leri/package'leri dışarıdan install etmeyi sağlar.

In [ ]:
#pip install numpy

In [1]:
import numpy as np

# Concatenation of the Arrays

[numpy.concatenate 01](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html),
[numpy.concatenate 02](https://sparkbyexamples.com/numpy/numpy-concatenate-arrays/),
[numpy.concatenate 03](https://www.tutorialspoint.com/numpy/numpy_concatenate.htm),
[numpy.concatenate 04](https://www.w3resource.com/numpy/manipulation/concatenate.php)

concatenate() fonksiyonu, iki veya daha fazla diziyi birleştirmek için kullanılır. 

Fonksiyonun ilk parametresi birleştirilecek dizilerin bir listesidir. 

İkinci parametre ise, birleştirme işleminin hangi eksen veya boyuta göre yapılacağını belirten bir parametredir.

Örneğin, axis=0 parametresi, dizilerin satır bazında (dikey birleştirme) birleştirilmesini, axis=1 parametresi ise sütun bazında (yatay birleştirme) birleştirilmesini sağlar.

In [1]:
x = np.array([1,2,3])

y = np.array([4,5,6])

In [2]:
x

array([1, 2, 3])

In [3]:
y

array([4, 5, 6])

In [4]:
xy = np.concatenate((x, y))

In [5]:
xy

array([1, 2, 3, 4, 5, 6])

In [7]:
a = np.array([[1,2], [1,2]])
a

array([[1, 2],
       [1, 2]])

In [8]:
b = np.array([[5,6], [7,8]])
b

array([[5, 6],
       [7, 8]])

In [9]:
np.concatenate((a,b))  # 4 * 2

array([[1, 2],
       [1, 2],
       [5, 6],
       [7, 8]])

In [10]:
np.concatenate((a,b), axis=1)    # 2 * 4

array([[1, 2, 5, 6],
       [1, 2, 7, 8]])

# Splitting of the Arrays

[numpy.split 01](https://www.w3resource.com/numpy/manipulation/split.php),
[numpy.split 02](https://sparkbyexamples.com/numpy/numpy-split-array/),
[numpy.split 03](https://numpy.org/doc/stable/reference/generated/numpy.array_split.html),
[numpy.split 04](https://www.w3schools.com/python/numpy/numpy_array_split.asp)

split(), numpy dizisini belirtilen eksende eşit parçalara bölmek için kullanılır.

In [12]:
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
np.split(a, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [14]:
np.split(a, 3)

ValueError: array split does not result in an equal division

In [15]:
np.array_split(a, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]

In [18]:
np.split(a, [4])

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [20]:
x = np.arange(20).reshape(5,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [21]:
np.split(x, [1,3], axis=0)

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [25]:
np.vsplit(x, [1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [22]:
np.split(x, [1,3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [24]:
np.hsplit(x, [1,3])

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

# Sorting of the Arrays

[numpy.sort 01](https://www.w3schools.com/python/numpy/numpy_array_sort.asp),
[numpy.sort 02](https://sparkbyexamples.com/python/numpy-sort-arrays-examples/),
[numpy.sort 03](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.sort.html),
[numpy.sort 04](https://www.geeksforgeeks.org/how-to-sort-a-numpy-array-python/)

sort(), numerik ya da alfabetik array elemanlarını, numerik veya alfabetik sıralarına göre sıralamasını yapar.

In [27]:
a = np.array([2,1,4,3,5])
a

array([2, 1, 4, 3, 5])

In [29]:
np.sort(a, axis=-1)

array([1, 2, 3, 4, 5])

In [31]:
a.sort()
a

array([1, 2, 3, 4, 5])

In [34]:
myarr = np.random.randint(5,100,(3,3))
myarr

array([[90, 26, 24],
       [19, 70, 43],
       [73, 72, 18]])

In [35]:
np.sort(myarr, axis=0)

array([[19, 26, 18],
       [73, 70, 24],
       [90, 72, 43]])

In [36]:
np.sort(myarr, axis=1)

array([[24, 26, 90],
       [19, 43, 70],
       [18, 72, 73]])

In [37]:
np.sort(myarr, axis=None)

array([18, 19, 24, 26, 43, 70, 72, 73, 90])

# Numpy Indexing & Selection

[INDEXING & SLICING Source 01](https://jakevdp.github.io/PythonDataScienceHandbook/03.02-data-indexing-and-selection.html),
[INDEXING & SLICING Source 02](https://www.kite.com/python/answers/how-to-select-an-element-by-index-from-a-numpy-array-in-python),
[INDEXING & SLICING Source 03](https://www.w3schools.com/python/numpy/numpy_array_indexing.asp),
[INDEXING & SLICING Source 04](https://www.pluralsight.com/guides/working-numpy-arrays-indexing-slicing-guide),
[INDEXING & SLICING Source 05](https://www.brainstobytes.com/hands-on-numpy-iii-indexing-and-slicing/),
[INDEXING & SLICING Source 06](https://www.geeksforgeeks.org/numpy-indexing/),
[INDEXING & SLICING Source 07](https://www.tutorialspoint.com/numpy/numpy_advanced_indexing.htm),
[INDEXING & SLICING Source 08](https://towardsdatascience.com/numpy-indexing-explained-c376abb2440d),
[INDEXING & SLICING Video Source 01](https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/),
[INDEXING & SLICING Video Source 02](https://www.youtube.com/watch?v=9nbBTaz2qXI),
[INDEXING & SLICING Video Source 03](https://www.youtube.com/watch?v=E1OFcMnU40o)

NumPy dizilerinde belirli bir elemana erişmek için, dizi adını takiben köşeli parantez içinde ilgili elemanın indeks numarasını belirtiriz.Örn; myarr[indexno]

İndeks numaraları 0'dan başlar, yani ilk elemanın indeksi 0'dır ve diğer elemanların indeks numaraları sırasıyla 1, 2, 3, gibi artar.

Ayrıca negatif indeksleme de kullanabiliriz. Negatif indeksleme, NumPy dizilerinde sondan başlayarak elemanlara erişmek için kullanılır. Son elemanın indeksi -1'dir ve önceki elemanların indeksleri sırayla -2, -3, gibi devam eder.

2 boyutlu NumPy dizilerinde, belirli bir elemana erişmek için satır ve sütun numaralarını kullanırız. Bu şekilde erişim için myarr[satırno, sütunno] formatı kullanılır.

3 boyutlu NumPy dizilerinde ise, elemana erişmek için derinlik, satır ve sütun numaralarını kullanırız. Yani erişim için myarr[derinlikno, satırno, sütunno] formatı kullanılır.

## Bracket Indexing & Selection

Bir dizinin bir veya birkaç öğesini seçmenin en basit yolu, python listelerindeki gibi yapılır.

Indexing: Tek bir elemana erişmek için kullanılır. Dizi elemanlarına sıfırdan başlayan bir index numarası ile erişilir. Örneğin, a[0] ifadesi, a dizisinin ilk elemanını verir.

Slicing: Dizinin alt kümesini seçmek için kullanılır. Dizinin belirli bir alt kümesini seçmek için [start:stop:step] sözdizimi kullanılır. Başlangıç ve bitiş indexleri belirtilmezse, varsayılan olarak başlangıç sıfır ve bitiş dizinin son elemanıdır.

In [42]:
arr = np.arange(24)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
arr[5]

5

In [44]:
arr[-1]

23

In [45]:
arr[23]

23

In [46]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [47]:
arr[:5]

array([0, 1, 2, 3, 4])

In [48]:
arr[1::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [50]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

## Indexing a 2D Array (Matrices)

![image.png](https://i.ibb.co/pvdHbBm/numpy-index.png)

![image-2.png](https://i.ibb.co/jJPp6hk/numpy-indexing2.png)

[SOURCE01](https://medium.com/@msjahid/numpy-array-indexing-slicing-23b70abb8433),
[SOURCE02](https://iq.opengenus.org/2d-array-in-numpy/)

In [51]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr_2d[1]

array([4, 5, 6])

In [55]:
arr_2d[1][2]

6

In [56]:
arr_2d[1][-1]

6

## Slicing a 2D Array (Matrices)

![image-2.png](https://i.ibb.co/64DGhj7/Numpy-index.jpg)

[SOURCE](https://stackoverflow.com/questions/16096753/python-array-slicing-how-can-2d-array-slicing-be-implemented)

![image.png](https://i.ibb.co/xmcGm9C/numpy-index1.png)

[SOURCE](https://scipy-lectures.org/intro/numpy/array_object.html)

[SOURCE](http://cs-tklab.na-inet.jp/~tkouya/python/scipy-lectures/intro/numpy/array_object.html)

![image-2.png](https://i.ibb.co/bHYsGLb/numpy-indexing-1.png)

In [57]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [59]:
arr_2d[2]

array([7, 8, 9])

In [61]:
arr_2d[2:]

array([[7, 8, 9]])

In [64]:
arr_2d[:, 1]

array([2, 5, 8])

In [65]:
arr_2d[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [67]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
arr_2d[1,1] = 100
arr_2d

array([[  1,   2,   3],
       [  4, 100,   6],
       [  7,   8,   9]])

## Fancy Indexing

Fancy Indexing, NumPy dizilerinde, bir veya daha fazla koşula veya belirtilen indeksler listesine göre dizideki belirli elemanlara erişmek için kullanılan bir indeksleme yöntemidir.

Bu yöntemde, köşeli parantez içinde bir liste veya dizi kullanarak, ilgili dizinin belirli elemanlarına erişebilirsiniz. Bu indeksleme yöntemi, normal indeksleme yöntemlerine göre daha esnek ve güçlüdür.

[SOURCE 01](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html#:~:text=Fancy%20indexing%20is%20conceptually%20simple,random.),
[SOURCE 02](https://notes.tahamaddam.com/coding/numpy/numpy-fancy-indexing), 
[SOURCE 03](https://stackoverflow.com/questions/52485840/numpy-fancy-indexing-with-tuples?rq=1),
[VIDEO SOURCE](https://www.youtube.com/watch?v=WpXH4PzDtYA)

In [72]:
a = np.arange(0,30,3)
a

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [73]:
a[1]

3

In [74]:
a[3]

9

In [75]:
a[5]

15

In [77]:
[a[1], a[3], a[5]]

[3, 9, 15]

In [78]:
index_list = [1,3,5]

In [79]:
a[index_list]

array([ 3,  9, 15])

In [ ]:
# iki boyutta fancy

In [80]:
arr = np.arange(100).reshape(10,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [81]:
arr[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
arr[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [84]:
arr[[2,4,6,8]]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [85]:
arr[[6,4,2,7]]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [87]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [86]:
arr[0,1]

1

In [88]:
arr[[1,2], [0,3]]

array([10, 23])

In [89]:
arr[[0,2,3],[0,1,3]]

array([ 0, 21, 33])

## Using Basic Index & Fancy Index Together

In [90]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
arr[1, [1,3]]

array([11, 13])

In [93]:
arr[[0,9],[1]]

array([ 1, 91])

In [94]:
arr[[0,-1],[1]]

array([ 1, 91])

## Using Basic Slicing & Fancy Index Together

In [95]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [98]:
arr[:, [8,9]]

array([[ 8,  9],
       [18, 19],
       [28, 29],
       [38, 39],
       [48, 49],
       [58, 59],
       [68, 69],
       [78, 79],
       [88, 89],
       [98, 99]])

In [99]:
arr[:, [-2,-1]]

array([[ 8,  9],
       [18, 19],
       [28, 29],
       [38, 39],
       [48, 49],
       [58, 59],
       [68, 69],
       [78, 79],
       [88, 89],
       [98, 99]])

In [101]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [100]:
arr[1:3, [1,2]]

array([[11, 12],
       [21, 22]])

In [102]:
arr[1:3, 1:3]

array([[11, 12],
       [21, 22]])

## Selection on a Condition

In [127]:
myarr =np.random.randint(1,50,5)
myarr

array([13, 38, 46,  2, 22])

In [128]:
myarr < 4

array([False, False, False,  True, False])

In [131]:
bool_arr2 = myarr < 4

In [132]:
myarr[bool_arr2]

array([2])

In [103]:
arr = np.arange(1,11)

In [104]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [106]:
bool_arr = arr > 4

In [108]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [133]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [134]:
arr[(arr !=3) & (arr !=4)]

array([ 1,  2,  5,  6,  7,  8,  9, 10])