In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pd.__version__

'1.4.4'

In [4]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_ve

In [6]:
pd.Series(dtype=float)

Series([], dtype: float64)

In [7]:
d = [1,2,3,4,5]

In [9]:
seri = pd.Series(d)

In [10]:
type(seri)

pandas.core.series.Series

In [11]:
seri = pd.Series([1,2,3,4,5])
seri

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
seri.dtype

dtype('int64')

In [14]:
arr = np.array([1.5,2,"a"])
arr

array(['1.5', '2', 'a'], dtype='<U32')

In [16]:
seri = pd.Series([1.5,2]).astype(int)
seri

0    1
1    2
dtype: int32

In [18]:
seri = pd.Series(d, index=["b","c","a", "d","b"])
seri

b    1
c    2
a    3
d    4
b    5
dtype: int64

In [19]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
pd.Series(arr)

ValueError: Data must be 1-dimensional

In [21]:
pd.DataFrame(arr)

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [22]:
seri = np.array([0,1,2,3,4])

In [23]:
seri

array([0, 1, 2, 3, 4])

In [24]:
seri_x = pd.Series(seri)

In [25]:
seri_x

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [27]:
data = {"ali":20, "veli":30, "mehmet":40}

seri = pd.Series(data)
seri

ali       20
veli      30
mehmet    40
dtype: int64

In [29]:
seri = pd.Series(data, index=["ali","ahmet","veli"])
seri

ali      20.0
ahmet     NaN
veli     30.0
dtype: float64

In [30]:
seri = pd.Series(10, index=[0,1,2])
seri

0    10
1    10
2    10
dtype: int64

In [31]:
pd.concat([seri_x,seri])

0     0
1     1
2     2
3     3
4     4
0    10
1    10
2    10
dtype: int64

In [32]:
seri = pd.Series([1,2,3,4], index=["Audi","BMW","Volvo","Mercedes"])
seri

Audi        1
BMW         2
Volvo       3
Mercedes    4
dtype: int64

In [33]:
seri[3]

4

In [34]:
seri["Mercedes"]

4

In [35]:
seri.index[3]

'Mercedes'

In [36]:
seri["Audi"]

1

In [37]:
seri = pd.Series(np.random.randint(0,50,6))
seri

0    33
1     2
2    19
3     7
4    20
5    35
dtype: int32

In [38]:
seri.dtype

dtype('int32')

In [39]:
seri.size

6

In [40]:
seri.ndim

1

In [41]:
seri.index

RangeIndex(start=0, stop=6, step=1)

In [42]:
seri.values

array([33,  2, 19,  7, 20, 35])

In [43]:
seri.head()

0    33
1     2
2    19
3     7
4    20
dtype: int32

In [44]:
list(seri.items())

[(0, 33), (1, 2), (2, 19), (3, 7), (4, 20), (5, 35)]

In [46]:
seri.sample(3) #default'i 1 dir.

4    20
0    33
5    35
dtype: int32

In [47]:
seri.sort_index(ascending=False)

5    35
4    20
3     7
2    19
1     2
0    33
dtype: int32

In [48]:
seri.sort_values()

1     2
3     7
2    19
4    20
0    33
5    35
dtype: int32

In [51]:
seri.isin([5,2])

0    False
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [52]:
data = [[1,2,3], [4,5,6]]
columns = ["A","B","C"]

In [54]:
df = pd.DataFrame(data=data, columns=columns)
df

A  B  C
0  1  2  3
1  4  5  6

In [55]:
data = [["a", 2, 3.5], ["b", 5, 6.5]]
columns = ["A","B","C"]

In [56]:
df = pd.DataFrame(data=data, columns=columns)
df

A  B    C
0  a  2  3.5
1  b  5  6.5

In [57]:
df.dtypes

A     object
B      int64
C    float64
dtype: object

In [58]:
df.apply(type)

TypeError: copy() missing 1 required positional argument: 'self'

In [60]:
arr = np.arange(1,27,3).reshape(3,3)
arr

array([[ 1,  4,  7],
       [10, 13, 16],
       [19, 22, 25]])

In [65]:
df = pd.DataFrame(data=arr, columns=["A1","A2","A3"], index=["B1","B2","B3"])
df

A1  A2  A3
B1   1   4   7
B2  10  13  16
B3  19  22  25

In [66]:
data = {"Name": ["Ali","Veli","Ahmet"],"Age":[20,30,40]}

In [67]:
df = pd.DataFrame(data)
df

Name  Age
0    Ali   20
1   Veli   30
2  Ahmet   40

In [68]:
df.head(2)

Name  Age
0   Ali   20
1  Veli   30

In [69]:
df.tail(1)

Name  Age
2  Ahmet   40

In [70]:
df.sample(2)

Name  Age
1  Veli   30
0   Ali   20

In [71]:
df.columns

Index(['Name', 'Age'], dtype='object')

In [72]:
for i in df.columns:
    print(i)

Name
Age


In [73]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [74]:
max([i for i in df["Age"]])

40

In [75]:
df.Age.max()

40

In [76]:
df.Age.mean()

30.0

In [77]:
df["Age"].min()

20

In [78]:
df.columns = ["isim","yas"]

In [79]:
df

isim  yas
0    Ali   20
1   Veli   30
2  Ahmet   40

In [80]:
df.index = ["a","b","c"]
df

isim  yas
a    Ali   20
b   Veli   30
c  Ahmet   40

In [82]:
df.rename(columns={"isim":"Name", "yas":"Age"}, inplace=True)
df

Name  Age
a    Ali   20
b   Veli   30
c  Ahmet   40

In [83]:
df.shape

(3, 2)

In [84]:
df.shape[0] #1 dersek de 2 degerini verir sutun sayisini

3