In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [4]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://www.scipy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as `np`::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide a

In [6]:
np.arange.__doc__

'arange([start,] stop[, step,], dtype=None, *, like=None)\n\n    Return evenly spaced values within a given interval.\n\n    Values are generated within the half-open interval ``[start, stop)``\n    (in other words, the interval including `start` but excluding `stop`).\n    For integer arguments the function is equivalent to the Python built-in\n    `range` function, but returns an ndarray rather than a list.\n\n    When using a non-integer step, such as 0.1, the results will often not\n    be consistent.  It is better to use `numpy.linspace` for these cases.\n\n    Parameters\n    ----------\n    start : integer or real, optional\n        Start of interval.  The interval includes this value.  The default\n        start value is 0.\n    stop : integer or real\n        End of interval.  The interval does not include this value, except\n        in some cases where `step` is not an integer and floating point\n        round-off affects the length of `out`.\n    step : integer or real, opti

In [7]:
import time

In [8]:
time.time()

1680207956.1287718

In [9]:
start=time.time()

In [10]:
start

1680208030.7868962

In [12]:
size=10000000

l1=range(size)
l2=range(size)

a1 = np.arange(size)
a2 = np.arange(size)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took:" , (time.time() - start) * 1000)

start = time.time()
result = a1+a2
print("numpy took: ", (time.time() - start) * 1000) 

python list took: 2231.5022945404053
numpy took:  197.47138023376465


In [13]:
import sys

In [14]:
sys.getsizeof(5555)

28

In [17]:
l = range(1000)

print(sys.getsizeof(5))
print(sys.getsizeof(5)*len(l))

a=np.arange(1000)

print(a.itemsize)
print(a.itemsize*a.size)

28
28000
4
4000


In [18]:
a=[1,2,3,4]
b=[4,3,2,1]

In [19]:
ab=[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])

ab

[4, 6, 6, 4]

In [22]:
a1=np.array(a)
a2=np.array(b)

In [23]:
a1*a2

array([4, 6, 6, 4])

In [24]:
a1/a2

array([0.25      , 0.66666667, 1.5       , 4.        ])

In [25]:
a1 + a2

array([5, 5, 5, 5])

In [26]:
a1-a2

array([-3, -1,  1,  3])

# 1.array

In [28]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [29]:
np.array(mylist)

array([1, 2, 3])

In [30]:
np.array([1,2,3])

array([1, 2, 3])

In [32]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [33]:
mylist2 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

In [34]:
mylist2

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [35]:
myarray=np.array(mylist2)

In [36]:
myarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# 2.shape & reshape

In [37]:
myarray.shape

(4, 3)

In [38]:
myarray.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
myarray.reshape(12).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [41]:
myarray.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
myarray.reshape(3, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 3. ndim

In [50]:
mylist = list(range(0,12))

In [45]:
mylist

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47]

In [51]:
myarray = np.array(mylist)

In [48]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [52]:
myarray.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
myarray = np.array(mylist, ndmin=4)

In [55]:
myarray

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]]])

# 4.dytpe & astype

In [56]:
my_int = np.array([1,2,3])
my_int

array([1, 2, 3])

In [57]:
my_int.dtype

dtype('int32')

In [58]:
my_float = np.array([1.,2.2,3,6,5])
my_float

array([1. , 2.2, 3. , 6. , 5. ])

In [59]:
my_float.dtype

dtype('float64')

In [60]:
my_string = np.array([1.,2.2,3,6,5,"a"])
my_string

array(['1.0', '2.2', '3', '6', '5', 'a'], dtype='<U32')

In [61]:
my_string.dtype

dtype('<U32')

In [63]:
x = np.array([1,2], dtype=np.float32)
print(x)
print(x.dtype)

[1. 2.]
float32


In [64]:
newx=x.astype("i")

print(newx)
print(newx.dtype)

[1 2]
int32


In [65]:
arr = np.array([0,1,2])
newarr=arr.astype(bool)

print(newarr)
print(newarr.dtype)

[False  True  True]
bool
